#cloud-config
# Adds SSH keys to the rancher user
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMCmo4bGBYEuoJ75BvzanBq0olKsUdBEtuODaf3+1Ba0Fmr7lgRQ8tscCiZ0pJn8mFgcz4vDxeXACMUXApElIXI8SQJhBWcge1/wbE/eLTtac0mEoJWNpifddlJLLYc0q2AG1mJgeraUFgvNp1rFowyKGJan1TKDeeL07BXT9yR38RGBEaWOI4suZn+uLJUZFUnZBfrSwsKxGUMUmICozt/+a3L9K7N58x/SVF9bP8WjpNCsH+yPYnqFrFUDOVjqeX8mQ+6ScPaIp98k3Ut5yzgXcVRtfOEO+Xag6qibqtD5fiWMjPqTZJZ+1fB3vZE55HO9XGiZRNFSqmnZo0mLjr ricardo@ricardopaiva.com
dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
